- name: Install Default Applications (With no-recommendeds)
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    install_recommends: false
  loop:
    - curl
    - zip
    - unzip
    - vim
    - git
    - tmux
    - docker-ce
    - docker-ce-cli
    - wmenu
    - cargo
    - alacritty
    - sway
    - autotiling # sway autotiling (bspwm like split behavior)
    - intellij-idea-ultimate
    - spotify-client
    - zsh
    - zsh-syntax-highlighting
    - zsh-autosuggestions
    - pulsemixer
    - pipewire-audio
    - wireplumber
    - console-data
    - fzf
    - fastfetch
    - node-npm
    - libfuse2t64 # required for some AppImages(including: Vesktop)
    - fuse3 # required for some AppImages(including: Vesktop)
    - xwayland
    - xdg-desktop-portal-wlr
    - ntfs-3g
- name: Install Default Applications (With recommendeds)
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    install_recommends: true
  loop:
    - qutebrowser-qtwebengine
