- name: Install Default Applications
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    install_recommends: false
  loop:
    - curl
    - zip
    - unzip
    - vim
    - git
    - tmux
    - docker-ce
    - docker-ce-cli
    - wmenu
    - cargo
    - alacritty
    - qutebrowser-qtwebengine
    - sway
    - intellij-idea-ultimate
    - spotify-client
    - zsh
    - zsh-syntax-highlighting
    - zsh-autosuggestions
    - pulsemixer
    - pipewire-audio
    - wireplumber
    - console-data
